name: Task5
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task5:
    runs-on: ubuntu-latest
    steps:
      - name: Clone self
        uses: actions/checkout@v2
        with:
          ref: task5
      - name: Clone googletest
        uses: actions/checkout@v2
        with:
          repository: 'google/googletest'
          path: '3rdparty'
      - name: Build
        working-directory: task5
        run: tree ..; mkdir build; cd build; cmake ..; cmake --build .
