name: Task5
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: task5
      - uses: actions/checkout@v2
        with:
          repository: 'google/googletest'
          path: '3rdparty/googletest'
      - name: Build
        run: export GOOGLE_TEST_DIR=googletest; pwd; (cmake -DCMAKE_BINARY_DIR=cmake_build task5 && make C) | tree ./.. 
