name: Task5
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: task5
      - uses: actions/checkout@v2
        with:
          repository: 'google/googletest'
          path: '3rdparty/googletest'
      - name: Build
        working-directory: task5
        run: export GOOGLE_TEST_DIR=googletest; cmake .; make C
