name: Task5
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: task5
      - name: Build
        run: cd task5 | cmake . | make C | cd ..
      
