name: Task5
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  Task5:
    runs-on: ubuntu-latest
    steps:
      - name: Clone self
        uses: actions/checkout@v2
        with:
          ref: task5
      - name: Clone googletest
        uses: actions/checkout@v2
        with:
          repository: 'google/googletest'
          path: '${{github.workspace}}/task5/3rdparty'
      - name: Build
        working-directory: '${{github.workspace}}/task5'
        run: mkdir build; cd build; cmake ..; cmake --build .;
      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path:  './CTestExe'
          report-path: './report.xml'
          working-directory: './task5/bin/'
      - name: debug
        working-directory: '${{github.workspace}}/task5'
        run: tree
